name: publish release

on:
  issues:
    types:
      - labeled

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish_release:
    if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'release candidate') && github.event.label.name == 'approve release'
    runs-on: ubuntu-latest
    env:
      CHANGELOG_PATH: /tmp/CHANGELOG.md
      IS_PRERELEASE: ${{ contains(github.event.issue.labels.*.name, 'prerelease') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: release-candidate
          fetch-depth: 0
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: pnpm install --frozen-lockfile
        # Ensure npm 11.5.1 or later is installed for OICD.
      - run: |
          npm install -g npm@latest
          echo "Updated npm version: $(npm -v)"
      - run: pnpm release
        if: ${{ env.IS_PRERELEASE == 'false' }}
      - run: pnpm release --prerelease
        if: ${{ env.IS_PRERELEASE == 'true' }}
      - run: pnpm publish --publish-branch release-candidate
        if: ${{ env.IS_PRERELEASE == 'false' }}
      - run: pnpm publish --tag prerelease --publish-branch release-candidate
        if: ${{ env.IS_PRERELEASE == 'true' }}
      - run: echo NEW_TAG=$(git describe) >> $GITHUB_ENV
      - run: git push origin $NEW_TAG
      - run: pnpm dlx ts-node ./scripts/getLatestChangelog.ts > ${{ env.CHANGELOG_PATH }}
      - name: create release on GitHub
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          body_path: ${{ env.CHANGELOG_PATH }}
          commitish: main
          prerelease: ${{ env.IS_PRERELEASE }}
      - name: close issue
        uses: peter-evans/close-issue@05dff7ca07116e5707cfb3a3cd4af7bb5e43524c # v3.0.2
      - name: delete branch
        run: git push origin :release-candidate
      - name: cherry-pick release commit
        run: |
          git checkout main
          git cherry-pick $NEW_TAG
      - name: craete pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          title: 'chore(release): ${{ env.NEW_TAG }}'
          branch: 'merge-release-${{ env.NEW_TAG }}'
